version: "3.9"

networks:
  internal_net:
    driver: bridge

services:
  mongo:
    image: mongo:5
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal_net

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal_net

  backend-api:
    build: ./backend-api
    container_name: backend-api
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/devops
      - ENABLE_FILE_LOGS=true
      - SERVICE_NAME=backend-api
      - JWT_SECRET=mysecret

    ports:
      - "5002:5000" # host:container
    depends_on:
      - mongo
    volumes:
      - ./logs/backend-api:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend-api:5000/api/health/ready"]
      interval: 10s
      timeout: 15s
      retries: 10
    networks:
      - internal_net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      - PORT=5001
      - MONGO_URL=mongodb://mongo:27017/devops
      - JWT_SECRET=mysecret
      - ENABLE_FILE_LOGS=true
      - SERVICE_NAME=auth-service
    volumes:
      - ./logs/auth-service:/app/logs
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://auth-service:5001/api/auth/ready"]
      interval: 10s
      timeout: 15s
      retries: 10
    networks:
      - internal_net

  worker-service:
    build: ./worker-service
    container_name: worker-service
    environment:
      - REDIS_HOST=redis
      - ENABLE_FILE_LOGS=true
      - SERVICE_NAME=worker-service
    volumes:
      - ./logs/worker-service:/app/logs
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://worker-service:6000/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal_net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend-api
      - auth-service
    networks:
      - internal_net

volumes:
  mongo_data:
